### ISSUE TITLE
How to set twitter:image?

### ISSUE THREAD

**Issue by mklueh** [harlan-zw/nuxt-og-image#1]
### Details

Hello,

is it somehow possible to set the same og:image generated by this library as the twitter:image as well?

**Comment by harlan-zw** [comment]
Hey @mklueh 

You only need to set a `twitter:image` if it differs from the `og:image`. Are you asking if this package could generate different images for both?

**Comment by harlan-zw** [comment]
Going to close since there wasn't a response. Feel free to re-open with more details.

**Comment by mklueh** [comment]
Sorry, forgot to answer. You helped me already, I wasn't aware that twitter tags are optional :)

**Comment by TranHoang-Dev** [comment]
HI @mklueh  and @harlan-zw 
I'm trying to set twitter:image with Nuxt 3
Could u guys can help me a little by teach me how to do that, sorry for bother anw

**Comment by harlan-zw** [comment]
> HI @mklueh and @harlan-zw I'm trying to set twitter:image with Nuxt 3, but dont know where to setting to change my og:image to twitter:image Could u guys can help me a little by teach me how to do that, sorry for bother anw

Not sure what you mean, is this related to using this module? If not, just use useSeoMeta, see https://nuxt.com/docs/api/composables/use-seo-meta#useseometa

**Comment by TranHoang-Dev** [comment]
Sorry for not give u a full background,
I'm using Nuxt3, and i was install your module(nuxt-og-image).
I have created a ~components/OgImage/PaperHand.vue
And put it into my page view like this
<img width="407" alt="image" src="https://github.com/harlan-zw/nuxt-og-image/assets/94815430/085fe422-6d1e-47c5-861b-f3cebef1e353">

But i'm not sure when i share this page to twitter, the image gonna show up because this just is og:image not twitter:image

**Comment by harlan-zw** [comment]
> Sorry for not give u a full background, I'm using Nuxt3, and i was install your module(nuxt-og-image). I have created a ~components/OgImage/PaperHand.vue And put it into my page view like this <img alt="image" width="407" src="https://user-images.githubusercontent.com/94815430/256516338-085fe422-6d1e-47c5-861b-f3cebef1e353.png">
> 
> But i'm not sure when i share this page to twitter, the image gonna show up because this just is og:image not twitter:image

It will also set the twitter image, it's just called og image because that's what people know. Feel free to view the page source. If you still have issues feel free to get in touch on discord.

**Comment by TranHoang-Dev** [comment]
Thanks for giving me your time
