### ISSUE TITLE
Failed to create og image: Wasm has not been initialized. Call `initWasm()` function.

### ISSUE THREAD

**Issue by xdeq** [harlan-zw/nuxt-og-image#103]
### Describe the bug

A week ago, the og image pre-renderer started giving an error (**Cloudflare Pages**):

`Failed to create og image: Wasm has not been initialized. Call 'initWasm()' function.`

No changes were made to the project, the error started to appear after simple rebuild. No error locally.

`ogImage` config contains only a custom font.

### System / Nuxt Info

```Shell
Cloudflare Pages
Node: 18.12.1
Nuxt: 3.7.2
nuxt-og-image: 2.2.0
```

**Comment by harlan-zw** [comment]
This seems to be fixed in the v3 of the module.

<img src="https://nuxt-og-image-playground.pages.dev/__og-image__/image/og.png?title=Hello+Cloudflare+Pages+%F0%9F%91%8B&description=This+is+a+test+of+Cloudflare+Pages+provider&theme=%23f6821f">

Let me know if you have issues with it.
