### ISSUE TITLE
`Cache-Control: max-age` bug with cloudflare-kv-binding

### ISSUE THREAD

**Issue by maximepvrt** [harlan-zw/nuxt-og-image#104]
### Describe the bug

@harlan-zw, After the new release that fixed the cache-control value (PR https://github.com/harlan-zw/nuxt-og-image/pull/102), the Nuxter website was updated by @Atinux.

However, I noticed that the max-age value is set 1000 times larger than expected. I have reviewed your repository, Nitro, and Unstorage, but unfortunately, I was unable to locate the source of this issue.

![Capture d’écran 2023-10-28 à 14 38 49](https://github.com/harlan-zw/nuxt-og-image/assets/1840026/4e975b45-7268-40b1-92c9-60473ba90476)

**Comment by harlan-zw** [comment]
Thanks for the follow-up @maximepvrt, it seems like a bug in your PR that I missed, basically the `cacheTtl` time is a millisecond value, Cache-Control is configured with seconds, so we just need to `/ 1000`.

Looking at this though I noticed there is some inconsistencies elsewhere, should hopefully be clearer https://github.com/harlan-zw/nuxt-og-image/commit/5fd812e9930d7f0a05522c0d346a49876f07caf2.
