### ISSUE TITLE
 Cannot resolve "./resvgjs.android-arm64.node" from "/workspaces/website/node_modules/.pnpm/@resvg+resvg-js@2.6.0/node_modules/@resvg/resvg-js/js-binding.js" and externals are not allowed!

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-og-image#108]
### Describe the bug

Hello,

When building this PR, https://github.com/unjs/website/pull/182, with NITRO_PRESET=cloudflare_pages pnpm run build, the building failed becauseof this 

```
 Cannot resolve "./resvgjs.android-arm64.node" from "/workspaces/website/node_modules/.pnpm/@resvg+resvg-js@2.6.0/node_modules/@resvg/resvg-js/js-binding.js" and externals are not allowed!
```

### System / Nuxt Info

```Shell
/
```

**Comment by harlan-zw** [comment]
This should be solved with the v3.

Let me know if you still have issues.

**Comment by hckhanh** [comment]
This is still happen in v3.0.3

**Comment by harlan-zw** [comment]
The issue is you're likely trying to deploy from your local host to a machine that has a different operating system.
