### ISSUE TITLE
The current pre-release version cannot be installed in an arm64 CPU

### ISSUE THREAD

**Issue by schneider-carlo** [harlan-zw/nuxt-og-image#118]
### Describe the bug

The current pre-release version cannot be installed in an arm64 CPU. 
After executing yarn install, the next error is coming:

`@img/sharp-wasm32@0.33.0: The CPU architecture "arm64" is incompatible with this module.`

My package.json has these 2 Dev Dependencies:

```
"devDependencies": {
    "nuxt": "3.8.2",
    "nuxt-og-image": "3.0.0-beta.39"
}
```

### Reproduction

git clone git@github.com:schneider-carlo/nuxt-3-starter.git

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-` (had to remove nuxt-og-image to let the yarn install work)
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Hi, please use `3.0.0-beta.40`, still putting the finishing touches on it.
