### ISSUE TITLE
Support `css-inline` in non-node environments

### ISSUE THREAD

**Issue by harlan-zw** [harlan-zw/nuxt-og-image#119]
### Describe the bug

Currently not possible due to https://github.com/Stranger6667/css-inline/issues/260

**Comment by Stranger6667** [comment]
Now css-inline is distributed under new name - https://www.npmjs.com/package/@css-inline/css-inline

also, the options are now camel case as napi renames them by default (hopefully it is not a big issue).

if there are some platforms that are not supported by css-inline but you need them, please, let me know

**Comment by harlan-zw** [comment]
Thank you for your hard work @Stranger6667! I will try and get this implemented within the next few days

**Comment by Stranger6667** [comment]
Happy to do so, @harlan-zw!


An update - it seems like I need to fix some packages a bit first. Local installation with `@css-inline/css-inline` in `package.json` and `yarn install`:

```
error Couldn't find package "@css-inline/css-inline-darwin-arm64@0.12.0" required by "@css-inline/css-inline@0.12.0" on the "npm" registry.
```

**Comment by Stranger6667** [comment]
0.12.1 should work, but I didn’t yet check it myself

**Comment by harlan-zw** [comment]
Confirmed to be working in 3.0.0-rc.19 on:
- StackBlitz
- Netlify & Netlify Edge
- Vercel & Vercel Edge

I had some issues with Cloudflare but I think this is on my end. Will re-visit in the future but for now mark it as not compatible with Cloudflare.

Thanks again @Stranger6667 

:tada:

**Comment by Stranger6667** [comment]
Happy to see this released! :) Great work!
