### ISSUE TITLE
Making nuxt-icon work?

### ISSUE THREAD

**Issue by toniengelhardt** [harlan-zw/nuxt-og-image#12]
### Details

Is there a way to make the `<Icon />` component from `nuxt-icon` work with the 'browser' rendering mode? That would be super epic!

**Comment by harlan-zw** [comment]
Will investigate, would be good to support it

**Comment by toniengelhardt** [comment]
Maybe it's also an issue with the islands? 

You can see the problem here: https://github.com/toniengelhardt/webapicheck

It's a simple component with some Uno classes and some icons in `components/og/Default.island.vue`.

**Comment by harlan-zw** [comment]
Seems to be a core Nuxt issue with islands https://github.com/nuxt-modules/icon/issues/52

As a workaround, you can find the svg data on https://icones.js.org/ and paste it directly into the component

**Comment by toniengelhardt** [comment]
Perfect, thanks!

It's not super urgent, I'll wait for the fix in Nuxt.

**Comment by harlan-zw** [comment]
Seems to be working correctly with the latest version of things, going to close this off.

**Comment by toniengelhardt** [comment]
Thanks 🙏🏽
