### ISSUE TITLE
Type Errors in Computed Properties for 'stars' and 'downloads' in UnJs.vue

### ISSUE THREAD

**Issue by vasilistotskas** [harlan-zw/nuxt-og-image#128]
### Describe the bug

![Screenshot_2](https://github.com/harlan-zw/nuxt-og-image/assets/60323306/cddfc0d6-003a-4f2c-b1eb-425895c22476)

**Comment by harlan-zw** [comment]
Thanks, this is fixed in `v3.0.0-rc.12`
