### ISSUE TITLE
Chinese characters become placeholders with default renderer

### ISSUE THREAD

**Issue by kingyue737** [harlan-zw/nuxt-og-image#130]
### Describe the bug

Chinese characters become placeholders with default renderer

![image](https://github.com/harlan-zw/nuxt-og-image/assets/40021217/0f7136c0-632c-4bc7-a29a-4f26bc710c8c)

I'm new to nuxt-og-image. Is there a way to fix this? Or how to switch to chromium?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-n9xrzm

**Comment by harlan-zw** [comment]
Hi @kingyue737 

I've updated the documentation for this here: https://nuxtseo.com/og-image/guides/non-english-locales

The issue being the default font family (Inter) does not support these characters, there's an example in the docs as a workaround.
