### ISSUE TITLE
Except for HTML format, Chinese are not supported for display

### ISSUE THREAD

**Issue by pacmandoh** [harlan-zw/nuxt-og-image#132]
### Clear and concise description of the problem

<img width="324" alt="SCR-20240103-kfzv" src="https://github.com/harlan-zw/nuxt-og-image/assets/133459587/9602d39a-89c8-4ccc-884f-8b5fd62614fc">

### Suggested solution

Is my configuration incorrect, or is it not supported?

**Comment by harlan-zw** [comment]
See https://nuxtseo.com/og-image/guides/non-english-locales

**Comment by pacmandoh** [comment]
> See https://nuxtseo.com/og-image/guides/non-english-locales

sorry! thanks ❤️
