### ISSUE TITLE
Cache runtime images

### ISSUE THREAD

**Issue by sawa-ko** [harlan-zw/nuxt-og-image#17]
### Clear and concise description of the problem

Currently each time a domain is visited with an OG image generated by the package, it is rendered by the number of times the url is visited, which could have a negative effect on the server side.

### Suggested solution

It would be nice to have an option to cache the images generated by the package, with a certain expiration time, etc. In this way it would be possible to better control the resources needed for image generation.

This affects more when using the browser strategy, and not the Satori strategy.

### Alternative

None.		

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
This is now supported in the latest beta. See the [Caching](https://github.com/harlan-zw/nuxt-og-image#caching) documentation for more details.
