### ISSUE TITLE
CF Pages Build Error: The path is missing the og-image payload.

### ISSUE THREAD

**Issue by Zerro97** [harlan-zw/nuxt-og-image#18]
### Details

FIrst of all, thank you for making/maintaining this library :)

## Problem

While generating the project locally works fine, building the project in the Cloudflare Pages and Github Action logs out the following error:

```bash
ERROR  [nuxt] [request error] [unhandled] [500]  (500 The path ... is missing the og-image payload. (/api/og-image-options?path=...)) 
```

While some of my project pages are built using Nuxt Content, I noticed that the above error message happens to all of my pages so this might not be the Nuxt Content issue..

## Relevant config/code
`app.vue`
```vue
<div>
  // ...
  <SeoKit />
  <NuxtPage />
</div>
```

In all of my page files, added following:
```javascript
// useHead is a little different for individual pages but it generally is like below:
useHead({
  meta: [
    { name: 'keywords', content: keywords },
  ],
})

// useServerSeoMeta is a little different for individual pages but it generally is like below:
useServerSeoMeta({
  title: () => page.value?.title,
  description: () => page.value?.description,
})

defineOgImageStatic({
  component: 'MyOgImage',
  title: <string literal for different pages>,
  description: '',
  background: '#27272a',
})
```

In `components/islands/MyOgImage.vue`:
```vue
<script setup lang="ts">
const props = defineProps({
  title: String,
  description: String,
  backgroundColor: String,
})

</script>

<template>
  <div :class="[backgroundColor]" class="flex items-center justify-center w-full h-full text-white">
    <div class="flex items-center ml-20 mr-20">
      <img src="/favicon/apple-touch-icon.png" class="mr-8" width="200" height="200">
      <div class="flex flex-col">
        <h1 :style="{ fontSize: '70px' }" class="m-0">
          {{ title }}
        </h1>
        <p v-if="description" class="mt-4 text-2xl text-zinc-200">
          {{ description }}
        </p>
      </div>
    </div>
  </div>
</template>
```

In `nuxt.config.ts`:
```javascript
runtimeConfig: {
    public: {
      siteUrl: '...',
      siteName: '...',
      siteDescription: '...',
      language: 'en',
    },
  },
```

## What I tried

1. I tried `npx playwright install && nuxt generate` to see if the issue was caused by playwright but the problem still persisted.
2. I added the new `experimentalRuntimeBrowser: true` in my nuxt config, but it wasn't working.

---
Not sure why it works on local but fails in github action and cf pages...

**Comment by harlan-zw** [comment]
Version 1.5.0 _might_ work a little bit better with this. One thing to make sure of is that you are server-side rendering your pages

**Comment by harlan-zw** [comment]
Hi @Zerro97 

If you are still interested in this issue, please use ` v2.0.0-beta.21`, it is working with CloudFlare pages as far as I can tell.
