### ISSUE TITLE
Just a quick question, will this going to have an impack on the performance of the website?

### ISSUE THREAD

**Issue by BroJenuel** [harlan-zw/nuxt-og-image#19]
### Details

I am building a website that needs to be performant and I don't want to lose performance, but I really need something like this for customizing og images specially when sharing sites to social medias?

**Comment by harlan-zw** [comment]
If performance matters just pre-render all of the images at build time, all you need to do is pre-render the regular routes and use static og image definitions, as opposed to dynamic.

If you need dynamic, then the performance will be on the server itself, it wouldn't affect any metrics that Google cares about. 

Say you have a really low CPU server and there are hundreds of image requests coming in per second, then you might notice a slowdown on the server response time.
