### ISSUE TITLE
Failed to create a browser

### ISSUE THREAD

**Issue by toniengelhardt** [harlan-zw/nuxt-og-image#21]
### Details

I'm getting this error when I try to run the `nuxt generate` command on Digital Ocean:

![Screenshot 2023-03-03 at 19 06 44](https://user-images.githubusercontent.com/2703233/222808683-ff96ef3c-c58a-44b0-88fb-970c07f2b2e9.png)

Locally it works without issues and I've installed `playwright`. Do I need to install any other packages?

Using it like this:

```ts
defineOgImageStatic({
  component: 'OgMain',
  provider: 'browser',
})
```

nuxt-seo-kit 
Nuxt 3.2.3 with Nitro 2.2.3

**Comment by harlan-zw** [comment]
Hey @toniengelhardt 

Looks like the std-env package may not be detecting the digital ocean CI environment.

I've changed the logic to always try and install playwright as part of the generating step to get around this. Can you try 1.5.0 and let me know if it works any better

**Comment by toniengelhardt** [comment]
Thanks, I will try, but I didn't use the CI, I'm building it by hand via ssh in the console of the DO server.

**Comment by harlan-zw** [comment]
> Thanks, I will try, but I didn't use the CI, I'm building it by hand via ssh in the console of the DO server.

That would probably explain why then :laughing:

**Comment by harlan-zw** [comment]
> `???`
> 
> What do mean, it only works in a CI? Locally it works fine just with the generate command.
> 
> New version also fails:
> 
> ![Screenshot 2023-03-08 at 12 32 05](https://user-images.githubusercontent.com/2703233/223714425-e1a8a9ec-1881-433d-b961-d824629b6860.png)

Previously it only tried to install playwright for you in a CI environment. If you have playwright as a dependency and it's still failing, it is likely an environmental issue.

I've changed the code so the exception is thrown, you can try the latest version (1.5.2) and let me what it throws

**Comment by toniengelhardt** [comment]
Amazing! 

I think it is definitely better to expose the error.

It complained about `playwright` and after re-installing it works now. I think I missed the second line the first time to install the OS deps:

```bash
$ pnpm dlx create-playwright
$ sudo pnpm exec playwright install-deps
```

Thanks a lot 🙏🏽 🙏🏽 🙏🏽
