### ISSUE TITLE
Dev tools stopped working on 1.3.5 of nuxt-seo-kit

### ISSUE THREAD

**Issue by Flowko** [harlan-zw/nuxt-og-image#24]
### Describe the bug

it just stopped working after updating to the new version, tho everything else works fine.
just the integration with devtools `v0.2.5`:

![image](https://user-images.githubusercontent.com/35883748/225884667-40cfb2a8-48d3-4cb7-b9ad-49f0c0f2c6e9.png)
![image](https://user-images.githubusercontent.com/35883748/225884690-0d6f6d91-3808-4b91-b04d-b30dc55b6cb7.png)

i cant seem to reproduce it on stackblitz, as it throws errors when it loads:
![image](https://user-images.githubusercontent.com/35883748/225885406-979983d0-dcae-4430-b657-e54759cc25be.png)

### Reproduction

[Stack blitz reproduction](https://stackblitz.com/edit/nuxt-starter-uheyd6?file=package.json,nuxt.config.ts)

### System / Nuxt Info

```Shell
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`, `build`, `nitro`, `experimental`, `modules`, `runtimeConfig`, `css`, `typescript`, `image`, `i18n`, `apiParty`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27968280.9739e4d`, `nuxt-headlessui@1.1.1`, `@vueuse/nuxt@9.13.0`, `nuxt-icon@0.3.3`, `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/device@3.1.0`, `nuxt-swiper@1.0.1`, `@nuxt/devtools@0.2.5`, `@nuxtjs/tailwindcss@6.6.0`, `nuxt-api-party@0.10.0`
- Build Modules:    `-`
------------------------------
```

**Comment by harlan-zw** [comment]
Hm I think i synced it the latest edge release, could you try

`@nuxt/devtools-ui-kit-edge@^0.2.5-27981287.ed164c8`

**Comment by harlan-zw** [comment]
Oh yeah devtools doesn't actually work in stackblitz

If you're having issues locally use the local edge of devtools 

```
    "@nuxt/devtools-edge": "0.2.5-27981287.ed164c8",
```

There's a v0.3 coming soon which will sort this

**Comment by Flowko** [comment]
okay thanks

**Comment by harlan-zw** [comment]
Will keep this open until v0.3 is out

**Comment by harlan-zw** [comment]
v0.3 is out and dependency is locked to non-edge version in the latest beta now
