### ISSUE TITLE
[500] Intl.Segmenter does not exist. Please use import a polyfill

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-og-image#29]
### Describe the bug

Visualisation of `og.png` leads to the referenced error. 

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gdt6pi?file=pages/index.vue
Click on any "OG:IMAGE" link. 

### System / Nuxt Info

```Shell
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`
- Runtime Modules:  `nuxt-og-image@1.5.5`
- Build Modules:    `-`
------------------------------
```

**Comment by harlan-zw** [comment]
Can't seem to replicate it with the latest beta

https://stackblitz.com/edit/nuxt-starter-xccx6d?file=package.json

Could you verify?

**Comment by tmlmt** [comment]
It does not work on my end ://

![image](https://user-images.githubusercontent.com/10244927/227712498-5996cd19-8673-44b0-ab83-8fb4046a3d2b.png)

**Comment by harlan-zw** [comment]
> It does not work on my end ://
> 
> ![image](https://user-images.githubusercontent.com/10244927/227712498-5996cd19-8673-44b0-ab83-8fb4046a3d2b.png)

What browser are you using?

**Comment by tmlmt** [comment]
Good point ! 

- Firefox 111.0.1: does not work
- Chromium 111.0.5563.110: works !

**Comment by harlan-zw** [comment]
Looks like this can be solved with https://github.com/surferseo/intl-segmenter-polyfill

I tried testing this on Firefox outside of Stackblitz and it appears to work so I'm not sure if it makes sense to polyfill.

**Comment by tmlmt** [comment]
I copied the above-referenced stackblitz repro locally on my machine, and can confirm that it works fine with Firefox, so I also propose to close this one, and for future issues I'll avoid using Stackblitz for nuxt-og-image repros.
