### ISSUE TITLE
`description` is not taken into account if a description meta tag exists 

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-og-image#30]
Would love to provide a minimal repro but my attempt was stopped by #29. 

I wonder if this part of the code might explain this behavior: 
https://github.com/harlan-zw/nuxt-og-image/blob/7ad9a4505f8b47c0973baefb8e2fa9d4a99845be/src/runtime/nitro/utils-pure.ts#L33-L41

**Comment by harlan-zw** [comment]
Thanks! Should be fixed in 2.0.0-beta.4
