### ISSUE TITLE
does not work with app.baseURL

### ISSUE THREAD

**Issue by ww-lemon** [harlan-zw/nuxt-og-image#31]
### Describe the bug

in nuxt.config.js
```
{
  app: { baseUrl: 'asd' }
}
```
Error
GET http://localhost:PORT/api/og-image-options?path=/test 404 (Cannot find any route matching /api/og-image-options?path=/test.)

**Comment by harlan-zw** [comment]
I've pushed out a number of improveents to the baseURL handling in [2.0.0-beta.8](https://github.com/harlan-zw/nuxt-og-image/releases/tag/v2.0.0-beta.8)

Feel free to try it out and let me know if you have any issues
