### ISSUE TITLE
[Custom templates]: issues with use of images

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-og-image#33]
### Details

Hey @harlan-zw, I've tried to make a custom template and added an image, and ran into issues. Could you let me know if I'm doing anything wrong, or whether there might be a bug? 
cc @Sandros94: as requested. If this is any close to the issue you've been facing, or if you have any tips, please chip in :)

## Intro

For the issues described below: 
- I used an image located in the `/public` folder
- Things work fine in dev, but **not in prod**. Therefore I don't really know whether it really makes sense to give you a repro because it most likely won't show on e.g. Stackblitz: perhaps you could try on your end with a simple prod test? 

## Issue 1: with @nuxt/image-edge

- If I don't specify a `width` and a `height` (which I thought were optional attributes -- and again, it works in dev), then I get the following error: 
<img src="https://user-images.githubusercontent.com/10244927/227726993-eeddf9d4-481a-4c06-abe9-3278411f6ccd.jpeg" width="300">

- After I did, then I get an og.png image, but images are not shown (only the text -- title and description -- appear) 

## Issue 2: with a simple `<img>` tag

After remplacing the `<nuxt-img>` tag by a simple `<img>` tag to see if it would work better, I got the following error when building my app (I deploy to a node.js server with universal rendering): 

```
ERROR  [vite]: Rollup failed to resolve import "/images/screenshot.png" from "/var/www/mywebsite/components/islands/CustomOgImage.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

Note: the image is located in `/public/images/screenshot.png`

**Comment by harlan-zw** [comment]
Thanks for the detailed issue, I've attempted to replicate it without any success.

Would it be possible to share the component? I have a production image component working here: https://github.com/harlan-zw/nuxt-og-image/blob/main/.playground/components/islands/OgImageWithImage.vue which is loaded from https://github.com/harlan-zw/nuxt-og-image/blob/main/.playground/pages/satori/image.vue.

I run `nuxt build .playground` and all is working both at runtime and prerendered. Maybe I'm missing something

**Comment by tmlmt** [comment]
Hey @harlan-zw, thanks a lot for having had a try. 

I took some time to work on a repro, and, like you, I couldn't replicate. Even my full app builds fine on my local dev machine, but complains with the Vite Rollup error (see Issue 2) on my production machine... I ended up moving my images to `/assets`, importing them, and placing the imported src in `:src` and it works also in production. 

No idea why it refuses to import static (`/public`) images in my production environment ... if you have any idea, please let me know. Otherwise I think I should probably close this issue and reopen if I find something out. Let me know.

**Comment by harlan-zw** [comment]
I would like to know as well but I have no idea and don't have much capacity to dig into it, sorry.

I'll close for now, if someone else runs into this then I'll take a look
