### ISSUE TITLE
OG Image not writing the right header tags

### ISSUE THREAD

**Issue by BroJenuel** [harlan-zw/nuxt-og-image#37]
### Describe the bug

This is from live website
![image](https://user-images.githubusercontent.com/31676163/231400240-2f9b56b4-f2d5-4194-9cdc-9413a61cc52d.png)

But it does not work in LinkedIN since Linkedin format does it this way.
![image](https://user-images.githubusercontent.com/31676163/231400440-f0a8d5d0-c256-40b0-a43d-01bc47cc729c.png)

**Comment by harlan-zw** [comment]
Hey @BroJenuel, thanks for the issue!

I've tested your site with the LinkedIn Post Inspector tool and it seems like an issue with your site. For whatever reason you have a 206 redirect when the LinkedIn bot is requesting the page.

![image](https://user-images.githubusercontent.com/5326365/231688212-85e682d6-68f3-49ec-bfa2-d5eb47acb519.png)

I believe this is causing your issue, as the image is probably causing a 206 redirect as well and failing. The og image tags that it's generating are correct. Do you have any ideas why your server would be doing this?

I tested my personal site and it doesn't seem to have any issues. (https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fharlanzw.com)

![image](https://user-images.githubusercontent.com/5326365/231687676-8e7062c6-cbd1-4f49-9c87-051df47fb071.png)

**Comment by BroJenuel** [comment]
its actually works before,, It might be something to do with the new updates of nuxt? because I updated it to the latest version of nuxt.

**Comment by BroJenuel** [comment]
Im going to close this one, I have to recheck again, thanks taking the time checking this out. :)
