### ISSUE TITLE
404 Island component not found

### ISSUE THREAD

**Issue by luminous8** [harlan-zw/nuxt-og-image#40]
### Describe the bug

When going to http://localhost:9001/my_url/__og_image__/og.png i got a 404 error

(404 Island component not found: undefined(/api/og-image-html?path=/my_url&options={"path":"/my_url","component":"MyOgImage","width":1200,"height":630,"provider":"satori","static":true,"backgroundColor":"bg-green-500","description":"My+title."}))

here the code i use
```
defineOgImageStatic({
  component: 'MyOgImage',
  title: 'My title',
  backgroundColor: 'bg-green-500',
});
```
I've tried to define
```
component: 'IslandsMyOgImage',
```
but it didn't work either

### Reproduction

I'm following the tutorial describe here https://github.com/harlan-zw/nuxt-og-image

### System / Nuxt Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.59 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 9.6.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 112.0.5615.49
    Firefox: 111.0.1
    Safari: 16.0
```

**Comment by austriker27** [comment]
@luminous8 what was the resolution? I'm also following the tutorial/docs and getting the same error.

**Comment by luminous8** [comment]
@austriker27 Actually, nothing special. 
It worked when i started working on it later

My code is as simple as that

defineOgImageStatic({
  component: 'MyOgImage',
  propsName: propsContent
});

my component "MyOgImage" is in components/islands

Hope that helps

**Comment by boumanb** [comment]
I'm experiencing this issue currently.

In `components/islands/MyOgImage.vue`
```vue
<script setup lang="ts">
const props = defineProps({
  title: String,
})
</script>

<template>
  <div class="w-full h-full flex text-white bg-blue-500 items-center justify-center">
    <h1 :style="{ fontSize: '70px' }">
      {{ title }} 👋
    </h1>
  </div>
</template>
``` 

in `app.vue`
```vue
<template>
  <SeoKit />
  <OgImageStatic component="MyOgImage" />
  <NuxtPage />
</template>

<style>
html {
  font-family: $dt('font.sans');
}
</style>

```

Resulting in error
```
Vue warn]: Component <Anonymous> is missing template or render function.          12:26:18 AM
[12:26:18 AM] [nuxt] [request error] [unhandled] [404]  (404 Island component not found: undefined (/__nuxt_island/MyOgImage.........
```
