### ISSUE TITLE
Failed to parse declaration for textShadow property value

### ISSUE THREAD

**Issue by Bumbleboss** [harlan-zw/nuxt-og-image#43]
### Describe the bug

When using this value `-1px -1px 0 #ffffff, 1px -1px 0 #ffffff, -1px 1px 0 #ffffff, 1px 1px 0 #ffffff` for `textShadow`, I receive this error.

```
Failed to parse declaration "textShadow: -1px -1px 0 #ffffff,1px -1px 0 #ffffff,-1px 1px 0 #ffffff,1px 1px 0 #ffffff"
```

The issue isn't there in the Vercel playground [link](https://og-playground.vercel.app/?share=ZZJNb6MwEIb_ymiqVS40cRtCtlaaw3ZX6h721Eq9cCGxAXcNRmACacR_7xiXfqQXmHle2-_M2CfcGyGR40aoQ1wCNPao5e3p5GKAXKostxxmV4z9mAUedkrY_IwJ1VQ6ORJNtewn6uLfqpZ7q0xJ2t7otignNdEqK_9aWTROkqWV9SQ9t41V6fHOECyd_1d5l-z_Z7VpS3FntKlJv0jT9N2Vdj2oF8lhef0JPb31EjE20mGIy60LNs0h-9TZbYzrVYyeHJTsfpmeGAMG6xVE71KqtCZ-wRib0DQ8KJI6U65jt6fqZ6MZwGhHhlVicxC0-d9yPV_dzK9XehnNb-j08H4ehT65jMKXGLebhVvtC11QpT6i2zq7Km_5aCoOoW8QgObtpkNF0nhifKNW9vYhT4TpnHR5VfUwfhi4XgL4BsbkfMVH7rsfhu291NoE8GRqLTYLKpFqnf4YoKncM2iQn3AcNPKfdBj6N4Y8dImQuzZDnia6kQHKwjyrx2PlHqjtxozOcZf5p9hJgdzWrRwCtMmOVuTOvnPmOLwC).

There's a chance this could be an issue from this repository rather than Satori itself because [issue](https://github.com/vercel/satori/issues/441) was fixed in this release [0.4.13](https://github.com/vercel/satori/releases/0.4.13). Checking this repository, the current version for Satori is 0.4.14 so I am still confused 😅

**Comment by harlan-zw** [comment]
Hey @Bumbleboss, thanks for the issue.

Could you try the latest beta and see if the issue still exists [v2.0.0-beta.23](https://github.com/harlan-zw/nuxt-og-image/commit/79b822488d6e04d10a4af11d2fa84514faccb694).
