### ISSUE TITLE
Fetch failed - Error 500

### ISSUE THREAD

**Issue by luminous8** [harlan-zw/nuxt-og-image#47]
### Describe the bug

When loading the /__og_image__/og.png url on my production server i got an 500 error 
(Things works fine on my computer)

<img width="726" alt="Capture d’écran 2023-05-03 à 11 33 20" src="https://user-images.githubusercontent.com/17875165/235881634-8ab7e38e-9385-4302-9788-150add8cee88.png">

`[nuxt] [request error] [unhandled] [500] fetch failed (https://mydomain.com/api/og-image-options?path=/item/item-slug)
  at $fetchRaw2 (./.output/server/node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)
  at ./node_modules/nuxt-og-image/dist/runtime/nitro/middleware/og.png.mjs:16:19
  at Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1247:19)
  at Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1322:7)
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[nuxt] [request error] [unhandled] [500] fetch failed (https://mydomain.com/api/og-image-options?path=/item/item-slug)
  at $fetchRaw2 (./.output/server/node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)
  at ./node_modules/nuxt-og-image/dist/runtime/nitro/middleware/og.png.mjs:16:19
  at Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1247:19)
  at Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1322:7)
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"
[Vue Router warn]: No match found for location with path "/item/item-slug/__og_image__/og.png"`

Thanks for your help!

### Reproduction

/

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (6) x64 AMD EPYC 7542 32-Core Processor
    Memory: 8.55 GB / 15.63 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    npm: 9.6.2 - ~/.nvm/versions/node/v19.8.1/bin/npm
```

**Comment by harlan-zw** [comment]
Hi @luminous8, could you share what version you're using and anything else that would be useful for reproducing the error.

**Comment by luminous8** [comment]
Yes, sorry (I knew i was forgetting something)

I was using 1.5.7
and I've now migrated to the ^2.0.0-beta.30 (hopping it would fix the bug)

My code is fairly simple, I'm using 
`
defineOgImageStatic({
  component: 'MyOgImage',
  item: item,
});
`

and my component looks like this
`<script setup lang="ts">
const props = defineProps({
  job: Object,
});
</script>

<template>
  <div
    class="relative flex flex-col items-center justify-center w-full h-full p-12 bg-gray-200"
  >
    <div
      class="flex flex-col items-center justify-center w-full bg-white shadow-md rounded-xl p-14 h-max"
    >
    <div
      class="flex flex-col justify-between w-full pt-8 md:flex-row md:items-center"
    >
      <div class="flex">
        redacted text
      </div>
      <div class="flex text-right text-[24px] leading-3 mt-2 text-gray-500">
        redacted text
      </div>
    </div>
  </div>
</template>
`

**Comment by harlan-zw** [comment]
You can try to access the URL it's trying to fetch directly and see what 500 error is thrown

`http://localhost:3000/api/og-image-options?path=/item/item-slug`

**Comment by luminous8** [comment]
I'm getting an ERR_CONNECTION_TIMED_OUT in my browser (i've done the same in local and it works perfectly)

**Comment by harlan-zw** [comment]
Which nitro preset are you using and are you using `nuxt build` or `nuxt generate`?

**Comment by luminous8** [comment]
I'm using Nuxt build

**Comment by jfern01** [comment]
I'm having the exact same issue. Also using nuxt build.

**Comment by luminous8** [comment]
update on my side: it's really weird, it started working after a couple of hours - i haven't changed anything

**Comment by harlan-zw** [comment]
Hmm very strange! Feel free to re-open if it pops back up :)
