### ISSUE TITLE
Error when trying to build project

### ISSUE THREAD

**Issue by Bumbleboss** [harlan-zw/nuxt-og-image#48]
### Describe the bug

Build stops when facing this error.
![image](https://user-images.githubusercontent.com/22979938/236543421-fdbf3a7b-ad16-44ad-af2e-a462b7335925.png)

Could be related to previous issue #42 related to fonts
![image](https://user-images.githubusercontent.com/22979938/236543486-a4f96761-e472-422d-b5de-6fac7a146854.png)

On latest beta 2.0.0-beta.32

**Comment by harlan-zw** [comment]
Hmm weird, this is just a type issue. Could you try deleting your .nuxt folder and trying again? I can't seem to replicate the problem.

If it's still broken it may be a Nuxt core issue around how the module typings are generated. Would you be able to provide your config?

**Comment by Bumbleboss** [comment]
Deleted .nuxt folder, didn't work. I am using SEO kit along with latest og image beta.
```ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      ///
    }
  },

  extends: [
    'nuxt-seo-kit'
  ],

  ogImage: {
    fonts: [
      'Manrope:500',
      {
        name: 'optieinstein',
        weight: 800,
        path: '/fonts/OPTIEinstein_black.woff',
      }
    ]
  },

  modules: [
    '@nuxt/content',
    '@nuxt/image-edge',
    'nuxt-og-image'
  ],

  app: {
    head: {
      ///
    }
  }
})
```

**Comment by Bumbleboss** [comment]
Hello, I wanted to give an update on the issue. I have tried reproducing it with
this setup using `yarn generate` and the error is there.

https://stackblitz.com/edit/github-ocxs1d-hbxtdw

The generated type in `.nuxt/types/schema.d.ts`
- using custom font: `Array<string|>`
- without custom font: `Array<string>`

**Comment by harlan-zw** [comment]
Upstream issue in untyped https://github.com/unjs/untyped/pull/96

Once this fix is merged then Nuxt will use it and the issue will be fixed. Will keep open until then.

**Comment by harlan-zw** [comment]
2.0.0-beta.45 also fixes this :)
