### ISSUE TITLE
Using `defineOgImageScreenshot()` with no prerendering on Vercel

### ISSUE THREAD

**Issue by sewalsh** [harlan-zw/nuxt-og-image#6]
### Details

This is a fantastic library!

I'm able to generate static screenshots, but I'd like to be able to dynamically generate some on Vercel.

Locally (Mac OS), using `defineOgImageScreenshot()` for dynamic generation of images works fine as I have all the necessary dependencies available system wide.

Vercel serves me an empty 204 response.

Is there a configuration option I'm missing? I've ensured `playwright` is part of build step but I'm unsure if this is available to the app once deployed.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7760319/216409363-478bb6b7-dc6b-40f7-8d76-0a4e949eba3b.png">

**Comment by juno-w** [comment]
Hi, I got the same issue as yours. I can't get it dynamically generate screenshot on Vercel. Works fine locally.

**Comment by harlan-zw** [comment]
Hey guys, currently it's not supported to take browser screenshots at runtime. This is because you need to have a chromium binary and it's very heavy and slow.

You should look into using the Satori provider if you need runtime images.

Saying that I will support it under a flag, might be a few days before I can take a look though

**Comment by harlan-zw** [comment]
In 1.4.4 you can try enabling the `experimentalRuntimeBrowser` config. You may need to explicitly add `playwright` as a dependency

**Comment by juno-w** [comment]
I opt for the `defineOgImageStatic` because the playwright is very slow and heavy indeed.

**Comment by harlan-zw** [comment]
Going to close, flag is available if anyone is brave enough to try.
