### ISSUE TITLE
How to use OgImageDynamic getting data from an API

### ISSUE THREAD

**Issue by titogarrido** [harlan-zw/nuxt-og-image#60]
### Details

Hi!

I have a nuxt 3 page that fetches a project data from an external API. This data includes a project cover that I want to set as my OGImage.

I will paste here some snippets and what I am doing:

```javascript
// This function fetches the project data. 
// The cover value is "project.value.full_cover" that returns a string like http://localhost:9000/projects/image.jpg
async function getProject() {
  await $api
    .get(`/posts/${project_id}`)
    .then((response) => {
      project.value = response.data;
    })
    .catch((error) => {
      console.log(error);
      router.push("/404");
    });
}
```

```javascript
// I am calling the getProject() during the Mount
onMounted(async () => {
  await getProject();
```

I have created a Component on `@/components/islands/OgImageWithImage.vue`:
```javascript
<template>
<div>
  <div>
    <img :src="image_path" width="1200" height="630">
  </div>
</div>
</template>

<script setup>
const props = defineProps({
  path: String,
  title: String,
  description: String,
  image_path: String,
})
</script>
```

The idea is to show my cover image as OGImage.

This is my resumed project component:
```javascript
<template>
  <LoadingComponent v-if="loading"></LoadingComponent>
  <div v-if="!loading">
  <!-- Project layout goes here -->
  </div>
  <OgImageDynamic
    component="OgImageWithImage"
    title="Hello world"
    :image_path="project.full_cover"
  />
</template
```

Now I am having trouble to pass this dynamic data to my OgImageDynamic. It does not show up on the "Options" section or it does not update to the fetched value.

What am I missing here?

Thanks!

**Comment by harlan-zw** [comment]
Hey @titogarrido, thanks for the issue.

Your problem is that you're not loading your project data server-side. The OG image only runs server side so it won't get your project data.

You can fix this simply by getting the project top-level.

```ts
<script setup>
const project = await getProject();
</script>
<template>
 <OgImageDynamic
    component="OgImageWithImage"
    title="Hello world"
    :image_path="project.full_cover"
  />
</template>
```

**Comment by titogarrido** [comment]
Do you mean I just need to move the <script setup> tag to the top of my vue component or do I need to create a /server/api/ route on my nuxt 3 project to call the external api?

My `getProject` function does not returns anything today:
```javascript
async function getProject() {
  await $api
    .get(`/posts/${project_id}`)
    .then((response) => {
      project.value = response.data;
    })
    .catch((error) => {
      console.log(error);
      router.push("/404");
    });
}
```
I will change it to also return response.data and put on another variable
```javascript
async function getProject() {
  await $api
    .get(`/posts/${project_id}`)
    .then((response) => {
      project.value = response.data;
      return response.data
    })
    .catch((error) => {
      console.log(error);
      router.push("/404");
    });
}
```

```javascript
const ogproject = await getProject()
```

I will test it.

Thanks!

Tito

**Comment by titogarrido** [comment]
Hi!

It worked using the /server/api implementation. As you said it needed to be fetched from the server side.

Thanks!

Tito
