### ISSUE TITLE
OgImageScreenshot breaks nuxt build/generate

### ISSUE THREAD

**Issue by stefangouldson** [harlan-zw/nuxt-og-image#62]
### Describe the bug

When using the either the defineOgImageScreenshot() function or the <OgImageScreenshot /> component, after running nuxt build or generate the command cannot be run again. This due to it not being able to full remove the .output/public which has some files that deny any access. 

In the public folder, the files that remain cannot be read or deleted despite me using admin access. The files tend to be the _payload.json in the root and each page folder that uses the screenshot. Also in the _nuxt folder, any images that appear on the page for the screenshot (which in example project is the navbar logo) have the same permission issue. 

![image](https://github.com/harlan-zw/nuxt-og-image/assets/54069519/4bf39aed-3480-4b02-82bb-6101d867715d)

Have attached a link to test project to reproduce issue. Have screen recording as well which I can send if needed

### Reproduction

https://github.com/stefangouldson/nuxt-ogimage-error

### System / Nuxt Info

```Shell
Windows 11
Node v18
nuxt: "^3.6.1",
nuxt-seo-kit: "^1.3.9"
```

**Comment by esoubiran-aneo** [comment]
Yes, have the exact same issue here.

**Comment by Barbapapazes** [comment]
Yes, I've the exact same issue here.

**Comment by harlan-zw** [comment]
> Yes, I've a similar issue here.
> 
> Details

Hey, please try v2.0.6

**Comment by Barbapapazes** [comment]
> > Yes, I've a similar issue here.
> > Details
> 
> Hey, please try v2.0.6

Hello, I still have the issue with 2.0.6

**Comment by Barbapapazes** [comment]
I also got this image 
![image](https://github.com/harlan-zw/nuxt-og-image/assets/45267552/ee269187-24c9-48f7-b04d-eab012f96e6e)

**Comment by gazreyn** [comment]
Yep, I'm having something similar. It seems to fail on nested routes. Just for some context on my set up. I'm using `2.0.6`. I had this working in another project using an old 2.0.0-beta45 build. The OG Images seem to generate fine when running in dev, just not when building.

I don't specify which routes I want to pre-render, instead I rely on 

```
nitro: {
  prerender: {
    crawlLinks: true,
  },
}
```

The pre-render only fails if I include and use defineOgImage. I also disable auto import in nuxt too (just in case it's any relevance). On that note, I do get a warning when using defineOgImage - `[nuxt] #imports should be transformed with real imports. There seems to be something wrong with the imports plugin.`

The error message I get is a bunch of
```[nuxt] [request error] [unhandled] [500] ENOTDIR: not a directory, open '/Users/macbookpro/Code/gazreyn/videocom-sb/.nuxt/cache/og-image/options/fr/blog/my-first-post'```

and for reference, what the cache folder looks like

![image](https://github.com/harlan-zw/nuxt-og-image/assets/26428458/bbb1999f-3146-48b7-bc11-21678f2547b2)

If there's anything else I can provide to help identify let me know. Likewise, if I'm doing something drastically wrong that I shouldn't be, would appreciate a little help.

**Comment by harlan-zw** [comment]
Okay, I think I found the bug, sorry for the confusion. There are two locations where the options cache was being set, I fixed it for one of them (runtime), but not the other (prerendering).

Please try v2.0.7

**Comment by harlan-zw** [comment]
> I also got this image ![image](https://user-images.githubusercontent.com/45267552/252133475-ee269187-24c9-48f7-b04d-eab012f96e6e.png)

Investigating this

**Comment by harlan-zw** [comment]
Seems to be an issue with the styles of screenshots, investigating

**Comment by gazreyn** [comment]
Awesome. Looks like all my problems are solved now! :D

**Comment by stefangouldson** [comment]
Can run nuxt generate no problem now with V2.0.9. Thanks 👍

**Comment by Barbapapazes** [comment]
It works but it seems CSS is not loading. I'm missing something?

![image](https://github.com/harlan-zw/nuxt-og-image/assets/45267552/282f9ef5-2a9a-45dc-b053-51eca39d45dc)

**Comment by harlan-zw** [comment]
Hey @Barbapapazes, would you mind trying [v2.0.10](https://github.com/harlan-zw/nuxt-og-image/releases/tag/v2.0.10)? This fixed the style issues for my doc sites.

**Comment by Barbapapazes** [comment]
> Hey @Barbapapazes, would you mind trying [v2.0.10](https://github.com/harlan-zw/nuxt-og-image/releases/tag/v2.0.10)? This fixed the style issues for my doc sites.

It works fine! Thanks 🚀
