### ISSUE TITLE
<style> tags' css ignored in rendering elements

### ISSUE THREAD

**Issue by kingtimm** [harlan-zw/nuxt-og-image#70]
### Describe the bug

Hi - what I'm experiencing is elements are rendered with tailwind utilities or in-line` style=""`. However, elements are rendered in the `<style>` section.

In the example repro, going to the OG image for Post and comparing to the template you can see the H1 isn't styled.

Steps to repro in the link below:

run `pnpm dev` and then visit `/post/__og_image__/og.png`.

The styles from the style tag in `MyTemplate.vue` are not applied.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kqfwbb

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v19.6.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.0
- Builder:          vite
- User Config:      modules, nitro, ogImage, site
- Runtime Modules:  nuxt-og-image@2.0.18, nuxt-icon@0.4.2
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hey, sorry for the delay in getting back to you. Thanks for the reproduction!

I've looked into this and I'm not entirely sure I understand the issue, seems like the `<h1>` is getting the style applied. 

Would you be able to provide me some more context?

Btw you may need the following as the attrs can mess up satori.

```ts
defineOptions({
  inheritAttrs: false,
})
```

**Comment by StefanH-AT** [comment]
Using 2.1.1 and css inside the style tag is still not getting applied

**Comment by harlan-zw** [comment]
Will need a reproduction to investigate further.
