### ISSUE TITLE
Cloudflare Pages: Failed to publish your Function. Got error: Uncaught TypeError: Class Constructor Aw cannot be invoked without 'new'

### ISSUE THREAD

**Issue by xdeq** [harlan-zw/nuxt-og-image#71]
### Describe the bug

![image](https://github.com/harlan-zw/nuxt-og-image/assets/14131173/097318ff-e4c6-43d5-ae96-702bcf1465e9)

After August 5, the use of `nuxt-og-image` started to cause an error deploying the Nuxt App using the Cloudflare Pages.

`Error: Failed to publish your Function. Got error: Uncaught TypeError: Class constructor Aw cannot be invoked without 'new'`

- Removing the library from the project fixes the error
- After August 5, no changes were made to the project that could have affected the occurrence of the error
- Package versions have not been changed
- Various manipulations with lock file and downgrade/upgrade versions did not produce any result
- Locally, everything's fine

`nuxt 3.6.5`
`nuxt-og-image 2.0.13` (2.0.18 also tested)

Cloudflare Preset - `cloudflare-pages`
Cloudflare Build System Version `2`
Cloudflare Compatibility date `2023-06-02`

**Comment by harlan-zw** [comment]
Thanks for the issue. Please try out v2.0.22.

**Comment by AleeeKoi** [comment]
I can confirm! it's working again. Thank you great job 🚀🚀🚀
