### ISSUE TITLE
Types error with `InputFontConfig`

### ISSUE THREAD

**Issue by Barbapapazes** [harlan-zw/nuxt-og-image#72]
### Describe the bug

The type is `(`${string}:${number}` | FontConfig)` but you provide `Roboto:400,700` in documentation, https://nuxtseo.com/og-image/api/config#fonts.

### Reproduction

/

**Comment by Barbapapazes** [comment]
Or the example is false.

**Comment by harlan-zw** [comment]
Thanks, have updated the docs.
