### ISSUE TITLE
WebSocket connection to 'ws://localhost:3000/__nuxt_og_image__/entry' failed

### ISSUE THREAD

**Issue by creazy231** [harlan-zw/nuxt-og-image#75]
### Describe the bug

Fresh install returns
```
WebSocket connection to 'ws://localhost:3000/__nuxt_og_image__/entry' failed
```
when visiting
```
http://localhost:3000/__og_image__
```

### System / Nuxt Info

```Shell
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, vite, experimental, sourcemap, components, imports, app, css, postcss, extends, modules, pinia, image, io, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, @pinia/nuxt@0.4.11, @nuxt/image@1.0.0-rc.1, @vueuse/nuxt@10.4.1, nuxt-socket-io@3.0.13
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
This _seems_ to be working better with Nuxt 3.7.1, let me know if you still have issues :)

**Comment by creazy231** [comment]
expecting the same issue using
```
"nuxt": "^3.7.1",
"@nuxtseo/module": "^2.0.0-beta.15",
```

**Comment by harlan-zw** [comment]
Thank you for confirming, I'll need to look into this again.

Weird thing is that I had this issue myself and now I can't replicate it anymore.. :thinking:

**Comment by creazy231** [comment]
just in general: since I changed from Node v16 to Node v18 I'm facing errors using localhost in projects. Working with 127.0.0.1 works fine. Didn't look into your codebase that much but maybe it's related to this in some kind?

**Comment by harlan-zw** [comment]
This seems to be working correctly now with latest versions. Let me know if not, I can revisit.
