### ISSUE TITLE
Using the TailwindCSS project configuration

### ISSUE THREAD

**Issue by Jorgagu** [harlan-zw/nuxt-og-image#87]
### Clear and concise description of the problem

Currently, the Nuxt OG image uses the TailwindCSS CDN with a default configuration.

I've suggested adding an option to use the local configuration used in the project, and more specifically the one used on the [TailwindCSS Nuxt module] (https://tailwindcss.nuxtjs.org/tailwind/config).

With the current configuration, I can't use my custom configuration with custom colors.

### Suggested solution

Add an option to retrieve the local configuration and pass it to the module.
Modify the [file html.ts at line 122](https://github.com/harlan-zw/nuxt-og-image/blob/1ac512a2b8643b3646f459e71d6d83d797630954/src/runtime/nitro/routes/html.ts#L122) to use the Tailwind project configuration.

**Comment by harlan-zw** [comment]
Hey, thanks for this suggestion.

This is now supported with the v3. Your custom theme classes should just work if you're using Tailwind or UnoCSS.

Let me know if you have any issues.
