### ISSUE TITLE
Array prop has duplicated vnodes when rendering SVG

### ISSUE THREAD

**Issue by manniL** [harlan-zw/nuxt-og-image#89]
### Describe the bug

When using an array property for the OG Image template, it's vnodes are doubled when rendering with satori.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/nuxt-og-image-issues-89?file=pages%2Findex.vue,components%2FOgImage%2FMyTemplate.vue)

1. Open the StackBlitz
2. Check the Template HTML - it should show [1,2,3]
3. Now check preview SVG. It shows [1,2,3,1,2,3]

![grafik](https://github.com/harlan-zw/nuxt-og-image/assets/640208/0a69ff90-eb3d-4ab0-8243-afc07ad363a3)

### System / Nuxt Info

- Operating System: Linux
- Node Version:     v18.14.2
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  pnpm@7.18.0
- nuxt-og-image@2.0.28

**Comment by harlan-zw** [comment]
Thanks for the issue and reproduction, will be fixed in next release.
