### ISSUE TITLE
unocss/tailwindcss cannot be used normally in the component

### ISSUE THREAD

**Issue by lxccc812** [harlan-zw/nuxt-og-image#94]
### Describe the bug

When I used the background graph property in the template component, it didn't display properly

```vue
<template>
    <div
        class="h-full w-full bg-[url(@/assets/img/og-image.png)]"
    >
    </div>
</template>
```

日志信息: 
```shell
[Vue Router warn]: No match found for location with path "/api/@/assets/img/og-image.png"
[Vue Router warn]: No match found for location with path "/api/@/assets/img/og-image.png"
[Vue Router warn]: No match found for location with path "/api/@/assets/img/og-image.png"
[Vue Router warn]: No match found for location with path "/api/@/assets/img/og-image.png"
```

Redundant `/api` paths appear in the path during parsing, causing the file to not be located correctly

### Reproduction

none

### System / Nuxt Info

```Shell
nuxt: 3.7.4
nuxt-og-image: 2.1.1
```

**Comment by harlan-zw** [comment]
Hi, thanks for the issue.

Unfortunately, any URLs that require bundling are not likely to work. You should instead relative image links from the `public` directory or use absolute image URLs.

You can read more here: https://nuxtseo.com/og-image/guides/icons-and-images
