### ISSUE TITLE
Support JPEG OG Images

### ISSUE THREAD

**Issue by adydetra** [harlan-zw/nuxt-og-image#95]
### Clear and concise description of the problem

By default **nuxt-og-image** will convert the result to **png**.

![image](https://github.com/harlan-zw/nuxt-og-image/assets/108399634/a5ef376a-048a-4f96-9234-794c2b0d39c8)

But sometimes I encounter cases where my bg color become transparent, including gradients. both vanilla CSS and tailwindcss. for example, I once shared via Discord.

And I found a solution after I changed some code. but in my opinion it is quite time consuming and requires a little logic even though it is just simple CSS styling.

in the sense that I need the results in jpg format, so there are no transparent colors.

### Suggested solution

I think it would be really cool if we could choose the image format in the configuration. examples of **png**, **jpg**, and **webp**.

maybe we can do the configuration in **nuxt.config.ts** or in **defineOgImage**.

**Comment by harlan-zw** [comment]
In v3 you'll definitely be able to do this with the browser renderer. For Satori I think the best option is to integrate with Nuxt Image somehow, will need to do some more research on this.

**Comment by harlan-zw** [comment]
This is now supported with the v3 rc.
