### ISSUE TITLE
disable flag in some pages

### ISSUE THREAD

**Issue by djixadin** [harlan-zw/nuxt-og-image#96]
### Details

i used    ``` <OgImage /> ``` in my default layout.. is there a way for me to disable it on some pages because on some pages i want to explicitly set ogImage and then as i do change it using useServerSeoMeta twitter image src remains the og version.. is there i way around this or i have to put that component in all pages but those where i want to override it

**Comment by harlan-zw** [comment]
Hi, in v3 you can use `defineOgImage(false)` to remove it, or just use `defineOgImage({ url: '/your-image.png' })` to replace it with another image.
